// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: "postgresql://postgres.vjihutfqsopearfhsggp:Manhique16%40@aws-0-eu-west-1.pooler.supabase.com:6543/postgres?pgbouncer=true",
  },
});
